build:
  version: "1.0"

loans:
  message: "Welcome to PROD "
  contactDetails:
    name: "Nitika - PROD"
    email: "nitika@eazybank.com"
  onCallSupport:
    - (555) 555-2444
    - (555) 523-7777

spring:
  config:
    activate:
      on-profile: "prod"