server:
  port: 8080
spring:
  application:
    name: "accounts" # Follow the same name that you gave in config server
  profiles:
    active: "prod"
    # we are only commenting out the below line because its not letting the docker to run, while testing bring this back
  config:
    import: "configserver:http://localhost:8071/"
    # We are using RabbitMQ here because what if we have 100 of microservices, then with refresh api of actuator we will have to invoke 100's of apis.
    # That is why we are using bus service of rabbitMQ, where we will hit the bus api only once and all the microservices configurations will get refreshed.
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # If no tables created, please create the table based on sql scripts
    show-sql: true # print all sql queries

management:
  endpoints:
    web:
      exposure:
        include: "*"   # We are telling springboot to expose all endpoint management related endpoints of actuator